import { and, desc, eq, isNull, lte } from "drizzle-orm";
import type { DbClient } from "../client";
import {
	monitoringProjects,
	monitoringPrompts,
	monitoringResults,
	monitoringSchedules,
} from "../schema/monitoring";
import type {
	NewMonitoringProject,
	NewMonitoringPrompt,
	NewMonitoringResult,
	NewMonitoringSchedule,
} from "../types";
import { requireFirstRow } from "./utils";

// Projects
export function createProject(db: DbClient, data: NewMonitoringProject) {
	return db
		.insert(monitoringProjects)
		.values(data)
		.returning()
		.then((rows) => requireFirstRow(rows, "monitoring.createProject"));
}

export function getProjectById(db: DbClient, id: string) {
	return db.query.monitoringProjects.findFirst({
		where: and(eq(monitoringProjects.id, id), isNull(monitoringProjects.deletedAt)),
		with: { prompts: true, schedules: true },
	});
}

/**
 * List every monitoring project in the system. Beacon runs single-tenant,
 * so every caller wants all projects. Soft-deleted projects are excluded.
 */
export function listAllProjects(db: DbClient) {
	return db.query.monitoringProjects.findMany({
		where: isNull(monitoringProjects.deletedAt),
		orderBy: desc(monitoringProjects.createdAt),
		with: { prompts: true, schedules: true },
	});
}

/**
 * Soft-delete: marks the project deleted without dropping its history.
 * Snapshots, mentions and the cascading FKs stay in place so the
 * historical record survives. Hard delete is intentionally not exposed.
 */
export function softDeleteProject(db: DbClient, id: string) {
	return db
		.update(monitoringProjects)
		.set({ deletedAt: new Date() })
		.where(and(eq(monitoringProjects.id, id), isNull(monitoringProjects.deletedAt)))
		.returning()
		.then((rows) => rows[0]);
}

// Prompts
export function createPrompt(db: DbClient, data: NewMonitoringPrompt) {
	return db
		.insert(monitoringPrompts)
		.values(data)
		.returning()
		.then((rows) => requireFirstRow(rows, "monitoring.createPrompt"));
}

export function getSuggestedPrompts(db: DbClient, projectId: string, limit = 20) {
	return db.query.monitoringPrompts.findMany({
		where: and(
			eq(monitoringPrompts.projectId, projectId),
			eq(monitoringPrompts.autoGenerated, true),
		),
		orderBy: desc(monitoringPrompts.createdAt),
		limit,
	});
}

export function getPromptsByProjectId(db: DbClient, projectId: string) {
	return db.query.monitoringPrompts.findMany({
		where: eq(monitoringPrompts.projectId, projectId),
	});
}

export function deletePrompt(db: DbClient, id: string) {
	return db
		.delete(monitoringPrompts)
		.where(eq(monitoringPrompts.id, id))
		.returning()
		.then((rows) => rows[0]);
}

// Results
export function createResult(db: DbClient, data: NewMonitoringResult) {
	return db
		.insert(monitoringResults)
		.values(data)
		.returning()
		.then((rows) => requireFirstRow(rows, "monitoring.createResult"));
}

export function getResultsByPromptId(
	db: DbClient,
	promptId: string,
	opts: { limit?: number; offset?: number } = {},
) {
	const { limit = 20, offset = 0 } = opts;
	return db.query.monitoringResults.findMany({
		where: eq(monitoringResults.promptId, promptId),
		orderBy: desc(monitoringResults.checkedAt),
		limit,
		offset,
	});
}

// Schedules
export function createSchedule(db: DbClient, data: NewMonitoringSchedule) {
	return db
		.insert(monitoringSchedules)
		.values(data)
		.returning()
		.then((rows) => requireFirstRow(rows, "monitoring.createSchedule"));
}

export function getSchedulesByProjectId(db: DbClient, projectId: string) {
	return db.query.monitoringSchedules.findMany({
		where: eq(monitoringSchedules.projectId, projectId),
	});
}

export function getNextSchedules(db: DbClient, before: Date) {
	return db.query.monitoringSchedules.findMany({
		where: and(lte(monitoringSchedules.nextRunAt, before), eq(monitoringSchedules.enabled, true)),
		with: { project: true },
	});
}

/**
 * Distinct project ids that have at least one enabled schedule. The daily
 * blanket sweep skips these — they are driven by the schedule dispatcher.
 */
export async function listProjectIdsWithEnabledSchedule(db: DbClient): Promise<string[]> {
	const rows = await db
		.selectDistinct({ projectId: monitoringSchedules.projectId })
		.from(monitoringSchedules)
		.where(eq(monitoringSchedules.enabled, true));
	return rows.map((r) => r.projectId);
}

export function updateScheduleAfterRun(db: DbClient, id: string, nextRunAt: Date) {
	return db
		.update(monitoringSchedules)
		.set({ lastRunAt: new Date(), nextRunAt })
		.where(eq(monitoringSchedules.id, id))
		.returning()
		.then((rows) => rows[0]);
}

export function updateSchedule(
	db: DbClient,
	id: string,
	updates: { frequency?: string; enabled?: boolean; nextRunAt?: Date },
) {
	return db
		.update(monitoringSchedules)
		.set(updates)
		.where(eq(monitoringSchedules.id, id))
		.returning()
		.then((rows) => rows[0]);
}

export function deleteSchedule(db: DbClient, id: string) {
	return db
		.delete(monitoringSchedules)
		.where(eq(monitoringSchedules.id, id))
		.returning()
		.then((rows) => rows[0]);
}
