name: Feature Request
description: Ein neues Feature vorschlagen
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Welches Problem soll gelöst werden?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Vorgeschlagene Lösung
      description: Wie sollte das Feature funktionieren?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Welche Alternativen wurden in Betracht gezogen?
    validations:
      required: false
