import { relations, sql } from "drizzle-orm";
import { boolean, index, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { competitors } from "./competitors";

export const monitoringProjects = pgTable("monitoring_projects", {
	id: uuid("id").primaryKey().defaultRandom(),
	name: text("name").notNull(),
	websiteUrl: text("website_url").notNull(),
	brandKeywords: text("brand_keywords").array().notNull(),
	competitorKeywords: text("competitor_keywords").array(),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true })
		.defaultNow()
		.$onUpdateFn(() => new Date()),
	deletedAt: timestamp("deleted_at", { withTimezone: true }),
});

export const monitoringPrompts = pgTable("monitoring_prompts", {
	id: uuid("id").primaryKey().defaultRandom(),
	projectId: uuid("project_id")
		.references(() => monitoringProjects.id, { onDelete: "cascade" })
		.notNull(),
	prompt: text("prompt").notNull(),
	category: text("category"), // "brand", "product", "comparison"
	autoGenerated: boolean("auto_generated").default(false),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const monitoringResults = pgTable(
	"monitoring_results",
	{
		id: uuid("id").primaryKey().defaultRandom(),
		promptId: uuid("prompt_id")
			.references(() => monitoringPrompts.id, { onDelete: "cascade" })
			.notNull(),
		engine: text("engine").notNull(), // "chatgpt", "perplexity", "gemini"
		responseText: text("response_text").notNull(),
		brandMentioned: boolean("brand_mentioned").notNull(),
		brandPosition: integer("brand_position"),
		urlsCited: text("urls_cited").array(),
		ourUrlCited: boolean("our_url_cited").notNull(),
		sentiment: text("sentiment"), // "positive", "neutral", "negative"
		checkedAt: timestamp("checked_at", { withTimezone: true }).defaultNow(),
		expiresAt: timestamp("expires_at", { withTimezone: true }).default(
			sql`NOW() + INTERVAL '90 days'`,
		),
	},
	(table) => [
		index("idx_monitoring_results_checked").on(table.checkedAt.desc()),
		index("idx_monitoring_results_prompt").on(table.promptId, table.checkedAt.desc()),
		index("idx_monitoring_results_expires_at")
			.on(table.expiresAt)
			.where(sql`${table.expiresAt} IS NOT NULL`),
	],
);

export const monitoringSchedules = pgTable(
	"monitoring_schedules",
	{
		id: uuid("id").primaryKey().defaultRandom(),
		projectId: uuid("project_id")
			.references(() => monitoringProjects.id, { onDelete: "cascade" })
			.notNull(),
		frequency: text("frequency").notNull(), // "daily", "weekly", "hourly"
		nextRunAt: timestamp("next_run_at", { withTimezone: true }).notNull(),
		lastRunAt: timestamp("last_run_at", { withTimezone: true }),
		enabled: boolean("enabled").notNull().default(true),
		updatedAt: timestamp("updated_at", { withTimezone: true })
			.defaultNow()
			.$onUpdateFn(() => new Date()),
	},
	(table) => [
		index("idx_monitoring_schedules_next").on(table.nextRunAt).where(sql`${table.enabled} = true`),
	],
);

// Relations
export const monitoringProjectsRelations = relations(monitoringProjects, ({ many }) => ({
	prompts: many(monitoringPrompts),
	schedules: many(monitoringSchedules),
	competitors: many(competitors),
}));

export const monitoringPromptsRelations = relations(monitoringPrompts, ({ one, many }) => ({
	project: one(monitoringProjects, {
		fields: [monitoringPrompts.projectId],
		references: [monitoringProjects.id],
	}),
	results: many(monitoringResults),
}));

export const monitoringResultsRelations = relations(monitoringResults, ({ one }) => ({
	prompt: one(monitoringPrompts, {
		fields: [monitoringResults.promptId],
		references: [monitoringPrompts.id],
	}),
}));

export const monitoringSchedulesRelations = relations(monitoringSchedules, ({ one }) => ({
	project: one(monitoringProjects, {
		fields: [monitoringSchedules.projectId],
		references: [monitoringProjects.id],
	}),
}));
